services:
  volt: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: volt
    environment:
      - TOKEN={TOKEN}
      - ENVIRONMENT={ENVIRONMENT}
      - CRON_SECRET={CRON_SECRET}
      - DB_URL={DB_URL}
    ports:
      - "8080:8080"