name: Deploy Discord Bot via Self-Hosted Runner

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    # This is the key change: it tells the job to run on your droplet
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # - name: Set up environment variables
    #   run: |
    #     echo "TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env
    #     echo "ENVIRONMENT=production" >> .env
    #     echo "DB_URL=${{ secrets.DB_URL }}" >> .env

    - name: Build and Restart Docker Compose
      run: |
        # --build will recreate the image using the new code
        # -d runs the containers in the background
        docker-compose up --build -d
